### PR TITLE
ISSUE-11-use-partial-import

### PR DESCRIPTION
**Pull request by JackHowa**
Closes #11

### CODE REVIEW

**Comment by JackHowa** [comment]
- We're already using the entryfile designation in news-theme to specify _index
- This is a performance improvement and standardization

**Comment by JackHowa** [comment]
After talking with @badmintonkid webpack has an issue when both _index and index.scss are there

**Review by brentmiller1973 — COMMENTED** [review]
Has this been tested locally with a full environment?  I'm just curious if this impacts bundle size at all.

**Review by badmintonkid — APPROVED** [review]
I did a quick test with this in CMG's repo and it looked correct. I'm seeing 14.2 kb gzipped css bundle size. CMG also has custom css that overrides stuff but I believe this one would be the combinations file.

One issue I do see is if some of the other themes clients are using index.scss. Do you know if any are? If not, this seems fine.

**Comment by JackHowa** [comment]
> One issue I do see is if some of the other themes clients are using index.scss. Do you know if any are? If not, this seems fine.

That's a good question. I wonder if there's a list of all of the themes implementations. I will search on GitHub

**Comment by JackHowa** [comment]
> I'm just curious if this impacts bundle size at all.

For me, it's a bit about technical debt as well. This oddity has caused confusion a couple of times when I've worked with devs.

**Review by beltrancaliz — APPROVED** [review]

**Comment by JackHowa** [comment]
hmm found this so far @badmintonkid 

Uses _index.scss not index.scss

- [x] cmg https://github.com/wapopartners/CMG-Themes-PageBuilder-Fusion-Features/blob/dev/blocks.json#L66
- [ ] mentor https://github.com/wapopartners/Mentor-PageBuilder-Fusion-Features/blob/dev/blocks.json#L70
- [x] core components https://github.com/WPMedia/Fusion-News-Theme/blob/master/blocks.json#L79

**Comment by RobinGiannattasio** [comment]
The `staging` branch is being deprecated in favor of `canary` per the standardization requirements of [PEN-1265](https://arcpublishing.atlassian.net/browse/PEN-1265)

**Comment by badmintonkid** [comment]
> hmm found this so far @badmintonkid
> 
> Uses _index.scss not index.scss
> 
> * [x]  cmg https://github.com/wapopartners/CMG-Themes-PageBuilder-Fusion-Features/blob/dev/blocks.json#L66
> * [ ]  mentor https://github.com/wapopartners/Mentor-PageBuilder-Fusion-Features/blob/dev/blocks.json#L70
> * [x]  core components https://github.com/WPMedia/Fusion-News-Theme/blob/master/blocks.json#L79

Ok, so someone will have to open a pr in mentor's repo and it will have to go to both sandbox and production envs before we can change this here. Or we'd have to ensure this stays in canary until they are switched over.

**Comment by JackHowa** [comment]
pr for mentor created. I don't know of any other potential repos affected https://github.com/wapopartners/Mentor-PageBuilder-Fusion-Features/pull/83

**Comment by badmintonkid** [comment]
> pr for mentor created. I don't know of any other potential repos affected [wapopartners/Mentor-PageBuilder-Fusion-Features#83](https://github.com/wapopartners/Mentor-PageBuilder-Fusion-Features/pull/83)

@JackHowa I think we should update the sass imports too. It looks like both CMG and CoreComponents have absolute paths for sass imports.

**Comment by JackHowa** [comment]
Cool updated -- thanks @badmintonkid

**Comment by JackHowa** [comment]
Will wait on deployment for mentor to merge this in and deploy canary. currently fix is in `dev` branch of mentor 
@nealmalkaniwapo @badmintonkid 

Uses _index.scss not index.scss

- [x] cmg https://github.com/wapopartners/CMG-Themes-PageBuilder-Fusion-Features/blob/dev/blocks.json#L66
- [x] mentor https://github.com/wapopartners/Mentor-PageBuilder-Fusion-Features/blob/dev/blocks.json#L70
- [x] core components https://github.com/WPMedia/Fusion-News-Theme/blob/master/blocks.json#L79

waiting on
https://github.com/wapopartners/Mentor-PageBuilder-Fusion-Features/pull/84

**Comment by ghost** [comment]
Thanks @JackHowa we are still waiting on approval from Mentor before we can deploy to prod. I will keep you posted.

**Comment by JackHowa** [comment]
released as 4.0.0-0 to canary tag. breaking because a potential bad import could be breaking

**Pull request merged**
